kind: Cluster
apiVersion:  kind.x.k8s.io/vlalpha4

nodes:
  --  role: control-plane
      image: kindest/node:v1.31.2
  --  role: control-plane
      image: kindest/node:v1.31.2
  --  role: control-plane
      image: kindest/node:v1.31.2
